title: "SageMaker HyperPod Experiment Collection"
summary: "SageMaker HyperPod の実験集です。"
topics: ["AWS", "SageMaker Hyperpod"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
