title: "ML Distributed Training/Inference - Experiment Collection"
summary: "分散学習・推論関連の実験集です。"
topics: ["AWS", "SageMaker Hyperpod", "Distributed Training", "Distributed Inference"]
published: false
price: 4000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - experiment-hyperpod-checkpointless-training
  - transformer-distributed-parallelism
  - pipeline-parallelism
#  - review
#  - background
#  - infrastructures
#  - orchestration
#  - aws-parallelcluster-tutorial
#  - resiliency
#  - amazon-sagemaker-hyperpod-resiliency
#  - amazon-sagemaker-hyperpod-slurm-tutorial
#  - amazon-sagemaker-hyperpod-slurm-ddp-on-cpu
#  - amazon-sagemaker-hyperpod-slurm-observability
#  - amazon-sagemaker-hyperpod-slurm-resiliency
#  - multi-gpu-processing-approaches
#  - appendix-optimizer
#  - appendix-vast-data-checkpoint-analysis
#  - appendix-network-topologies
#  - appendix-model-architectures
#  - appendix-ai-infrastructures
#  - llm-viewer
#  - deepseek

