title: "ML Distributed Training/Inference - Experiment Collection"
summary: "分散学習・推論関連の実験集です。"
topics: ["AWS", "SageMaker Hyperpod", "Distributed Training", "Distributed Inference"]
published: false
price: 4000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - background
  - infrastructures
  - orchestration
  - aws-parallelcluster-tutorial
  - resiliency
#  - appendix-optimizer
#  - appendix-vast-data-checkpoint-analysis
#  - appendix-network-topologies
#  - appendix-model-architectures
#  - appendix-ai-infrastructures
