title: "translated articles"
summary: "translated"
topics: ["translation"]
published: false
price: 10000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
  - hf-audio-course-ch5-intro
